server:
  port: 7080

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: hc-boot-demo
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: bzf_site_dev
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: bzf_site_dev
  config:
    import:
      - optional:nacos:hc-demo.yaml
